// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKBhBRa9dOM0RPRKf4bPpvAjeBg2brqyQ',
    appId: '1:648703873922:web:c1ad3e55a2fb3058b5b59b',
    messagingSenderId: '648703873922',
    projectId: 'notepad-f9305',
    authDomain: 'notepad-f9305.firebaseapp.com',
    storageBucket: 'notepad-f9305.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAABNsaumMohgiSC98_Iejx7_85A6vsW8A',
    appId: '1:648703873922:android:09b8450511979626b5b59b',
    messagingSenderId: '648703873922',
    projectId: 'notepad-f9305',
    storageBucket: 'notepad-f9305.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZEK0h9LP3eqQ33Z9gLCHK-rfu996_4gw',
    appId: '1:648703873922:ios:eada514793c6ea36b5b59b',
    messagingSenderId: '648703873922',
    projectId: 'notepad-f9305',
    storageBucket: 'notepad-f9305.appspot.com',
    iosClientId: '648703873922-7thp852cas9avs1nndecc4e6csrtdk7h.apps.googleusercontent.com',
    iosBundleId: 'com.example.notepad',
  );
}
